apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-tilt
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-tilt
spec:
  params:
    - name: run-image
      value: registry.gcp.ellin.net/tanzu-todo
  source:
    git:
      url: https://github.com/jeffellin/ASPNetToDo
      ref:
        branch: tilt 
